package com.junit2ndtask;


public class OrderItem {

    private Product product;
    private int quantity;

    // Constructor
    public OrderItem(Product product, int quantity) {
        this.product = product;
        this.quantity = quantity;
    }

    // Getters
    public Product getProduct() {
        return product;
    }

    public int getQuantity() {
        return quantity;
    }

    // Setters
    public void setProduct(Product product) {
        this.product = product;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    // Business method
    public double getItemTotal() {
        return product.getPrice() * quantity;
    }

    public void processItem() {
        product.reduceStock(quantity);
    }

    // toString (generated by @Data normally)
    @Override
    public String toString() {
        return "OrderItem [product=" + product + ", quantity=" + quantity + "]";
    }

    // equals and hashCode (simplified version)
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (!(obj instanceof OrderItem))
            return false;

        OrderItem other = (OrderItem) obj;

        return quantity == other.quantity &&
               (product != null ? product.equals(other.product) : other.product == null);
    }

    @Override
    public int hashCode() {
        int result = (product != null ? product.hashCode() : 0);
        result = 31 * result + quantity;
        return result;
    }
}
