-- creating a product table
CREATE TABLE product (
    prod_id SERIAL PRIMARY KEY,
    prod_name VARCHAR(100) NOT NULL,
    prod_desc TEXT,
    price NUMERIC(10,2) NOT NULL,
    prod_category VARCHAR(50) NOT NULL
);

-- Display all products
SELECT * FROM product;

-- Count products per category
SELECT prod_category, COUNT(*) AS countProd
FROM product
GROUP BY prod_category;


-- Count products per category and sort ascending
SELECT prod_category, COUNT(*) AS countProd
FROM product
GROUP BY prod_category
ORDER BY countProd ASC;

-- Get product with highest price
SELECT *
FROM product
WHERE price = (SELECT MAX(price) FROM product);


--find the second highest price
select * from product where price=(select max(price) from product where price<(
										select max(price) from product
									    ));

-- update the price of all electronic device so that new price is 10% lesser than the original price.
update product 
set price=price-(price* 0.1)
where prod_category='Electronics';

-- delete the product having prices less than average price.
delete from product
where price<(select avg(price) from product);

-- insert data in the table
INSERT INTO product (prod_id, prod_name, prod_desc, price, prod_category) VALUES
(701, 'Laptop Pro', '16GB RAM i7 Laptop', 75000, 'Electronics'),
(702, 'Smart TV', '55 inch 4K UHD TV', 52000, 'Electronics'),
(703, 'Headphones', 'Noise cancelling headset', 8500, 'Accessories'),
(704, 'Office Chair', 'Ergonomic office chair', 12000, 'Furniture'),
(705, 'Dining Table', 'Wooden 6 seater table', 30000, 'Furniture'),
(706, 'Refrigerator', 'Double door fridge', 45000, 'Appliances'),
(707, 'Microwave', 'Convection microwave oven', 15000, 'Appliances'),
(708, 'T-Shirt', 'Cotton round neck t-shirt', 799, 'Clothing'),
(709, 'Jeans', 'Slim fit denim jeans', 1999, 'Clothing'),
(710, 'Sneakers', 'Running sports shoes', 3499, 'Footwear'),
(711, 'Washing Machine', 'Fully automatic washer', 38000, 'Appliances'),
(712, 'Tablet', '10 inch Android tablet', 18000, 'Electronics'),
(713, 'Backpack', 'Waterproof travel bag', 2499, 'Accessories'),
(714, 'Watch', 'Analog wrist watch', 4999, 'Accessories'),
(715, 'Sofa', '3 seater leather sofa', 55000, 'Furniture'),
(716, 'Mixer Grinder', '750W kitchen mixer', 3999, 'Appliances'),
(717, 'Novel Book', 'Fiction bestseller novel', 599, 'Books'),
(718, 'Notebook', 'Hardcover ruled notebook', 299, 'Stationery'),
(719, 'Gaming Mouse', 'RGB wired gaming mouse', 1499, 'Electronics'),
(720, 'Water Bottle', 'Steel insulated bottle', 899, 'Home');


-- delete the product category wise whose price is less than average price in that specififc category.
SELECT * FROM product;


delete from product p
where price < (select avg(price) from product p1 where p1.prod_category=p.prod_category);

-- create a table fo order having  feilds like ord_id, ord_date,ord_type and propd_id as foreign key
-- also ensure that whenever a data changes in the parent table, it should get reflected in the child table.


create table orders(order_id integer primary key,
			order_date date,
			order_type varchar(20) not null,
			product_id integer,

		constraint fk_product
		foreign key (product_id)
		references product(prod_id)
)

select * from product;
select * from orders;

alter table  prders RENAME TO orders;

drop table orders;

TRUNCATE product CASCADE;

-- insert data in order table
INSERT INTO orders(order_id, order_date, order_type, product_id)
VALUES
(2001, '2025-02-15', 'Online', 701),
(2002, '2025-02-16', 'Offline', 701),
(2003, '2025-02-17', 'Wholesale', 701),
(2004, '2025-02-18', 'Online', 702),
(2005, '2025-02-19', 'Online', 702),
(2006, '2025-02-20', 'Offline', 703);

-- find the maximum soled product
select product_id, count(product_id) as total_count
from orders
group by product_id
limit 1;


-- ===================================================================================================
-- -------------------------------------------- DAY 2 of SQL(PL-SQL)------------------------------------------
-- ===================================================================================================


select * from product;

create index idx_prodname on product(prod_name);

SELECT o.*,
       p.*
FROM orders o
JOIN product p
ON o.product_id = p.prod_id;



-- 1. Fetch order details along with product name and price
select p.prod_name,o.*
from product p
inner join  orders o
on p.prod_id=o.product_id;
	
-- 2. Total revenue generated by each product



select p.prod_name, sum(p.price) as total_Amoumt
from product p
join orders o
on p.prod_id=o.product_id
group by p.prod_name;


-- 3. Products that have never been ordered

select p.*
from product p
left join orders o
on p.prod_id=o.product_id
where o.product_id is null;


-- 4. Products with more repeat orders than new orders


select product_id,count(*) from orders
group by product_id
having count(*)>1;

-- 5. Top 3 products based on number of orders
select * from product;
select * from orders;

select o.product_id,p.prod_name, COUNT(o.product_id) as totalSold
from orders o
inner join  product p
on p.prod_id=o.product_id
group by product_id,p.prod_name
order by totalSold desc
limit 3;


-- 6. Total revenue from 'new' and 'repeat' orders separately


-- 7. Month-wise total revenue
	select 
		TO_CHAR(o.order_date,'YYYY-MM') as month,
		sum(p.price) as total_revenue
	from orders o
	join product p
	on p.prod_id=o.product_id
	group by TO_CHAR(o.order_date,'YYYY-MM');

--Create a Function in PostgreSQL and call that fucntion.

	create or replace function add_numbers(a int, b int)
	returns int
	as $$
	begin
		return a+b;
	end;
	$$ language plpgsql;
	
	select add_numbers(5,12)

------------------------------------------------FUNTIONS-----------------------------------------------


--  Question: 1 create a function that takes the product name as input and returns the price


-- =============================================SYNTAX================================================

CREATE OR REPLACE FUNCTION returnprice(prod_name varchar(20))
RETURNS NUMERIC(5)
AS $$
BEGIN
	RETURN price;
end;
$$ langauge plpgsql;

-- ======================================= method - 1 ===============================================
CREATE OR REPLACE FUNCTION returnprice(pname varchar(20))
RETURNS table(price NUMERIC)

AS $$
BEGIN
	RETURN QUERY select price  from product where prod_name=pname;

end;
$$ language plpgsql;

-- ==========================================Method-2==================================================
CREATE OR REPLACE FUNCTION returnprice(pname varchar(20))
RETURNS NUMERIC(5)
AS $$
DECLARE prod_price NUMERIC(5);
BEGIN
	select price into prod_price from product where prod_name=pname;
	RETURN prod_price;
end;
$$ language plpgsql;

-- ==========================================Call the Function==================================================
select returnprice('Smart TV');





--  Question: 2 create a function that returns the table.

-- ======================================= method - 1 ===============================================
CREATE OR REPLACE FUNCTION returntable()
RETURNS table(prod_id integer, prod_name varchar(20), prod_desc varchar(50), price numeric(5),prod_category varchar(20))
AS $$
BEGIN
	RETURN QUERY select *  from product;
end;
$$ language plpgsql;

DROP FUNCTION returntable()

select * from product;

------------------------------------STORED PROCEDURE----------------------------------------------------





--  Question 1: Write a procedure that takes product fields as input and add new row in product table.
-- ======================================= method - 1 ===============================================
CREATE OR REPLACE PROCEDURE INSERTDATA (pid integer, pname varchar(20), pdesc varchar(50), price numeric(5), pcategory varchar(20))
AS $$
BEGIN
	insert into product values (pid, pname, pdesc, price, pcategory);
end;
$$ language plpgsql;


-- ==========================================Calling Procedure ==================================================
call INSERTDATA(722,'Headphones','Full Base headphones',3000,'Electronics');







-- Question 2: Wriite a procedure that takes the product id and discount price as inut and apply 
--             discounted price in all given prod id;


-- ======================================= method - 1 ===============================================
CREATE OR REPLACE PROCEDURE diwaliDiscountOnElectronic( pid integer, discountedPercentage integer)
AS $$

BEGIN
	update product set price=price-(price*(discountedPercentage/100)) where prod_id=pid;
end;
$$ language plpgsql;

select * from product;
call diwaliDiscountOnElectronic();


------------------------------------TRIGGERS----------------------------------------------------



-- Create accounts table having id, name and balance field
-- Create account_audit table having account_id, old_balance, new_balance, changed_on fields

CREATE TABLE accounts(a_id serial primary key,
					name varchar(20),
					balance Numeric);

CREATE TABLE account_audit(
account_id INT,
old_balance NUMERIC,
new_balance NUMERIC,
changed_on timestamp default current_timestamp
);


------------------------------------------function------------------------------------------------------
CREATE OR REPLACE FUNCTION log_balance_update()
RETURNS TRIGGER
AS $$
BEGIN
	INSERT INTO account_audit(account_id, old_balance, new_balance)
	VALUES(OLD.a_id, OLD.balance, NEW.balance);

	RETURN NEW;
END;
$$ LANGUAGE plpgsql;


------------------------------------------trigger------------------------------------------------------

CREATE TRIGGER balance_update_trigger
AFTER UPDATE ON accounts
FOR EACH ROW
WHEN (OLD.balance IS DISTINCT FROM NEW.balance)
EXECUTE FUNCTION log_balance_update();

----------------------------------------Inserting data in Accounts---------------------------------------

INSERT INTO accounts (name, balance) VALUES
('Rahul', 5000.50),
('Priya', 12000.00),
('Amit', 7500.75);

select * from accounts;
Update accounts set balance=30000.0 where a_id=1;

-- automatically inserted the data in account_audit when any update happend in account table. 
select * from account_audit;

----------------------------------------How to do execution plan---------------------------------------

explain select p.prod_name, sum(p.price) as total_Amoumt
from product p
join orders o
on p.prod_id=o.product_id
group by p.prod_name;


